name: Subset font files

on:
  workflow_dispatch:

jobs:
  subset_fonts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Fetch the remote output branch
      run: git fetch origin output
    - name: Merge remote output branch with local
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git merge --allow-unrelated-histories origin/output

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install fonttools
      run: pip install fonttools

    - name: Install brotli
      run: pip install brotli
      
    - name: Install lxml
      run: pip install lxml
      
    - name: Remove existing output files
      run: rm -r output_files/

    - name: Run the main script
      run: python main.py
    - name: Checkout output branch
      run: git checkout output
    - name: Add the output files
      run: git add output_files/


    - name: Commit the output files
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git commit -m "Add subsetted font files"

      
    - name: Push the output files to the output branch
      run: git push -f origin output
