name: Subset font files

on:
  workflow_dispatch:

jobs:
  subset_fonts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install fonttools
      run: pip install fonttools

    - name: Install brotli
      run: pip install brotli

    - name: Run the main script
      run: python main.py

    - name: Commit and push the output files
      uses: actions/git-client@v4
      with:
        args: add output_files/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Commit and push the output files
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git commit -m "Add subsetted font files"
      uses: actions/git-client@v4
      with:
        args: push -u origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
