name: Subset font files

on:
  push:
    branches:
      - main

jobs:
  subset_fonts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install fonttools
      run: pip install fonttools

    - name: Install brotli
      run: pip install brotli

    - name: Run the main script
      run: python main.py

    - name: Commit and push the output files
      run: |
        git add output_files/
        git commit -m "Add subsetted font files"
        git push origin output:output
